name: helm-chart
namespace: ingress-nginx

deployment:
  replicas: 3
  name: helmchartdeployment
  selector: helmchartselect
  container: helmchartcontainer
  image: rohithmarigowda/assignment

service:
  port: 8080
  name: helmchartservice
  
ingress:
  name: ingress
  className: nginx
