apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: {{ .Values.name }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  replicas: {{ .Values.deployment.replicas }} # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      imagePullSecrets:
        - name: my-docker-registry-secret
      containers:
        - name: {{ .Values.name }}-container 
          image: {{ .Values.deployment.image }} # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.service.port }} # The port that the container is running on in the cluster
